server:
  port: 7001
spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://192.168.231.136:3306/order?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.231.136
    port: 6379
    password: admin
    database: 0
  rabbitmq:
    host: localhost
    port: 5672
    #    开启发送端确认
    publisher-confirm-type: correlated
    #    开启发送端抵达队列的确认
    publisher-returns: true
    #    开启接收端手动确认
    listener:
      simple:
        acknowledge-mode: manual
    #    只要抵达队列，以异步发送优先回调上面的确认
    template:
      mandatory: true
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8333
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: "*"
seata:
  application-id: order
  tx-service-group: my_test_tx_group # 一定用这个默认的
  enabled: true
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: ""
      username: nacos
      password: nacos
dubbo:
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: 127.0.0.1:8848
    protocol: nacos
  consumer:
    check: false
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id